# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 13:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('condition', models.CharField(max_length=2)),
                ('districtname', models.CharField(max_length=128)),
            ],
        ),
    ]
