# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terroristevent',
            old_name='attackType',
            new_name='attack_type',
        ),
        migrations.RenameField(
            model_name='terroristevent',
            old_name='numCasualties',
            new_name='num_casualties',
        ),
        migrations.RenameField(
            model_name='terroristevent',
            old_name='numHostiles',
            new_name='num_hostiles',
        ),
        migrations.RenameField(
            model_name='trafficevent',
            old_name='numCasualties',
            new_name='num_casualties',
        ),
    ]
