# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 05:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_dengue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singapore',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id_0', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('iso', models.CharField(blank=True, max_length=3, null=True)),
                ('name_0', models.CharField(blank=True, max_length=75, null=True)),
                ('id_1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('name_1', models.CharField(blank=True, max_length=75, null=True)),
                ('hasc_1', models.CharField(blank=True, max_length=15, null=True)),
                ('ccn_1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cca_1', models.CharField(blank=True, max_length=254, null=True)),
                ('type_1', models.CharField(blank=True, max_length=50, null=True)),
                ('engtype_1', models.CharField(blank=True, max_length=50, null=True)),
                ('nl_name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('varname_1', models.CharField(blank=True, max_length=150, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'cms_singapore',
                'managed': False,
            },
        ),
    ]
