# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160311_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='terroristevent',
            name='name',
            field=models.CharField(default=b'', max_length=128),
        ),
        migrations.AddField(
            model_name='trafficevent',
            name='name',
            field=models.CharField(default=b'', max_length=128),
        ),
    ]
