# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160312_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtransactionlog',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Reporter'),
        ),
    ]
