# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160311_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dateRecorded',
            new_name='date_recorded',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='numInjured',
            new_name='num_injured',
        ),
        migrations.AddField(
            model_name='event',
            name='assistance_required',
            field=models.CharField(choices=[(b'AMB', b'Ambulance'), (b'RES', b'Rescue'), (b'EVA', b'Evacuation')], default='AMB', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='contact_number',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
