# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160311_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficevent',
            old_name='numVehicles',
            new_name='num_vehicles',
        ),
    ]
